version: '3.1'
services:
  mysql:
    image: mysql:8
    container_name: mysql
    command: mysqld --default-authentication-plugin=mysql_native_password --skip-mysqlx
    restart: unless-stopped
    network_mode: cloudbuild
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=password
    entrypoint: sh -c "echo 'CREATE DATABASE IF NOT EXISTS `basapp-replatform-test`; CREATE DATABASE IF NOT EXISTS `girovision-test`;' > /docker-entrypoint-initdb.d/init.sql; /usr/local/bin/docker-entrypoint.sh --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci"

  cloud_sql_proxy_basapp:
    image: gcr.io/cloudsql-docker/gce-proxy:1.26.0
    container_name: cloud_sql_proxy_basapp
    command: /cloud_sql_proxy -instances=${DATABASE_CONNECTION_NAME}=tcp:0.0.0.0:3306
    restart: unless-stopped
    network_mode: cloudbuild
    ports:
      - '3306:3306'

  cloud_sql_proxy_girovision:
    image: gcr.io/cloudsql-docker/gce-proxy:1.26.0
    container_name: cloud_sql_proxy_girovision
    command: /cloud_sql_proxy -instances=${DATABASE_GIROVISION_CONNECTION_NAME}=tcp:0.0.0.0:3306
    restart: unless-stopped
    network_mode: cloudbuild
    ports:
      - '3306:3306'

networks:
  default:
    external:
      name: cloudbuild
