export const errorCodes = {
  AUTHORIZATION_REQUIRED: 'AUTHORIZATION_REQUIRED',
  USEFUL_INFORMATION_NOT_FOUND: 'USEFUL_INFORMATION_NOT_FOUND',
  INVALID_SAME_CATEGORY_USEFUL_INFORMATION:
    'INVALID_SAME_CATEGORY_USEFUL_INFORMATION',
};
