export const errorCodes = {
  USERNAME_EXISTENT: 'USERNAME_EXISTENT',
  INVALID_RESERVATION_TYPE: 'INVALID_RESERVATION_TYPE',
  AUTHORIZED_USER_NOT_FOUND: 'AUTHORIZED_USER_NOT_FOUND',
  EMPTY_FIELD_USERNAME: 'EMPTY_FIELD_USERNAME',
  INVALID_FILE_EXTENSION: 'INVALID_FILE_EXTENSION',
  EMPTY_FIELDS: 'EMPTY_FIELDS',
};
