export const errorCodes = {
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  CONTACT_NOT_FOUND: 'CONTACT_NOT_FOUND',
  EXIST_CONTACT: 'EXIST_CONTACT',
  CONTACT_AND_USERNAME_ARE_THE_SAME: 'CONTACT_AND_USERNAME_ARE_THE_SAME',
  INVALID_ALERT_TYPE: 'INVALID_ALERT_TYPE',
};
