import { Prisma, PrismaClient } from '@prisma/client';
import { Model } from '../seed';
import {
  constants,
  customerEventCategory,
  eventType,
} from '../utils/constants';

const { TEST_COUNTRY_ID, BOLIVAR_ID, SAN_FERNANDO_ID, STATESMAN } = constants;
const { CONSTRUCTION_TEST_COUNTRY_ID, VISITAS_TEST_COUNTRY_ID } =
  customerEventCategory;
const { LIST_VISITORS, SUPPLIERS } = eventType;

const model: Model & { data: Prisma.EventTypeCreateManyInput[] } = {
  data: [
    {
      code: 'AA100',
      title: 'VISITAS',
      active: true,
      description: false,
      attachment: false,
      monitor: true,
      addToStatistics: true,
      notifyUser: true,
      notifySecurityChief: false,
      notifySecurityGuard: false,
      additionalNotifications: '',
      customerId: TEST_COUNTRY_ID,
      autoCancelAfterExpired: true,
      allowsMultipleAuthorized: false,
      requiresDni: false,
      isPermanent: false,
      lotFrom: null,
      lotTo: null,
      emergency: false,
      requiresPatent: false,
      generateQr: true,
      qrFormat: 4,
      reservation: false,
      eventCategoryId: CONSTRUCTION_TEST_COUNTRY_ID,
      notifyGiroVision: true,
      gvEntryTypeId: null,
      gvGuestTypeId: null,
      updatedById: STATESMAN,
    },
    {
      code: 'AA110',
      updatedById: STATESMAN,
      title: 'DELIVERY',
      active: true,
      description: false,
      attachment: false,
      monitor: true,
      addToStatistics: true,
      notifyUser: true,
      notifySecurityChief: false,
      notifySecurityGuard: false,
      additionalNotifications: '',
      customerId: TEST_COUNTRY_ID,
      autoCancelAfterExpired: true,
      allowsMultipleAuthorized: false,
      requiresDni: false,
      isPermanent: false,
      lotFrom: null,
      lotTo: null,
      emergency: false,
      requiresPatent: false,
      generateQr: false,
      reservation: false,
      notifyGiroVision: false,
      gvEntryTypeId: null,
      gvGuestTypeId: null,
    },
    {
      id: SUPPLIERS,
      code: 'AA130',
      updatedById: STATESMAN,
      title: 'PROVEEDORES',
      active: true,
      description: false,
      attachment: false,
      monitor: true,
      addToStatistics: true,
      notifyUser: true,
      notifySecurityChief: false,
      notifySecurityGuard: false,
      additionalNotifications: '',
      customerId: SAN_FERNANDO_ID,
      autoCancelAfterExpired: true,
      allowsMultipleAuthorized: false,
      requiresDni: false,
      isPermanent: false,
      lotFrom: null,
      lotTo: null,
      emergency: false,
      requiresPatent: false,
      generateQr: false,
      reservation: false,
      notifyGiroVision: false,
      gvEntryTypeId: null,
      gvGuestTypeId: null,
    },
    {
      code: 'AA135',
      updatedById: STATESMAN,
      title: 'REMIS',
      active: true,
      description: false,
      attachment: false,
      monitor: true,
      addToStatistics: true,
      notifyUser: true,
      notifySecurityChief: false,
      notifySecurityGuard: false,
      additionalNotifications: '',
      customerId: SAN_FERNANDO_ID,
      autoCancelAfterExpired: true,
      allowsMultipleAuthorized: false,
      requiresDni: false,
      isPermanent: false,
      lotFrom: null,
      lotTo: null,
      emergency: false,
      requiresPatent: false,
      generateQr: false,
      reservation: false,
      notifyGiroVision: true,
      gvEntryTypeId: null,
      gvGuestTypeId: null,
    },
    {
      code: 'AA150',
      updatedById: STATESMAN,
      title: 'COMPRAS POR INTERNET',
      active: true,
      description: false,
      attachment: false,
      monitor: true,
      addToStatistics: true,
      notifyUser: true,
      notifySecurityChief: false,
      notifySecurityGuard: false,
      additionalNotifications: '',
      customerId: SAN_FERNANDO_ID,
      autoCancelAfterExpired: false,
      allowsMultipleAuthorized: false,
      requiresDni: false,
      isPermanent: false,
      lotFrom: null,
      lotTo: null,
      emergency: false,
      requiresPatent: false,
      generateQr: false,
      reservation: false,
      notifyGiroVision: true,
      gvEntryTypeId: null,
      gvGuestTypeId: null,
    },
    {
      code: 'AA160',
      updatedById: STATESMAN,
      title: 'RETIRO DE OBJETOS',
      active: true,
      description: true,
      attachment: false,
      monitor: true,
      addToStatistics: true,
      notifyUser: true,
      notifySecurityChief: false,
      notifySecurityGuard: false,
      additionalNotifications: '',
      customerId: TEST_COUNTRY_ID,
      autoCancelAfterExpired: true,
      allowsMultipleAuthorized: false,
      requiresDni: false,
      isPermanent: false,
      lotFrom: null,
      lotTo: null,
      emergency: false,
      requiresPatent: false,
      generateQr: false,
      reservation: false,
      notifyGiroVision: true,
      gvEntryTypeId: null,
      gvGuestTypeId: null,
    },
    {
      code: 'AA165',
      updatedById: STATESMAN,
      title: 'SALIDA DE MENORES',
      active: false,
      description: true,
      attachment: false,
      monitor: true,
      addToStatistics: true,
      notifyUser: true,
      notifySecurityChief: false,
      notifySecurityGuard: false,
      additionalNotifications: '',
      customerId: TEST_COUNTRY_ID,
      autoCancelAfterExpired: true,
      allowsMultipleAuthorized: false,
      requiresDni: false,
      isPermanent: false,
      lotFrom: null,
      lotTo: null,
      emergency: false,
      requiresPatent: false,
      generateQr: false,
      reservation: false,
      notifyGiroVision: true,
      gvEntryTypeId: null,
      gvGuestTypeId: null,
    },
    {
      code: 'AA500',
      updatedById: STATESMAN,
      title: 'RUIDOS MOLESTOS',
      active: true,
      description: true,
      attachment: false,
      monitor: true,
      addToStatistics: true,
      notifyUser: true,
      notifySecurityChief: false,
      notifySecurityGuard: false,
      additionalNotifications: '',
      customerId: TEST_COUNTRY_ID,
      autoCancelAfterExpired: false,
      allowsMultipleAuthorized: false,
      requiresDni: false,
      isPermanent: false,
      lotFrom: null,
      lotTo: null,
      emergency: false,
      requiresPatent: false,
      generateQr: false,
      reservation: false,
      notifyGiroVision: false,
      gvEntryTypeId: null,
      gvGuestTypeId: null,
    },
    {
      code: 'AA510',
      updatedById: STATESMAN,
      title: 'ANIMALES SUELTOS',
      active: true,
      description: true,
      attachment: true,
      monitor: true,
      addToStatistics: true,
      notifyUser: true,
      notifySecurityChief: false,
      notifySecurityGuard: false,
      additionalNotifications: '',
      customerId: TEST_COUNTRY_ID,
      autoCancelAfterExpired: false,
      allowsMultipleAuthorized: false,
      requiresDni: false,
      isPermanent: false,
      lotFrom: null,
      lotTo: null,
      emergency: false,
      requiresPatent: false,
      generateQr: false,
      reservation: false,
      notifyGiroVision: false,
      gvEntryTypeId: null,
      gvGuestTypeId: null,
    },
    {
      code: 'AA515',
      updatedById: STATESMAN,
      title: 'EXCESO DE VELOCIDAD',
      active: true,
      description: true,
      attachment: false,
      monitor: true,
      addToStatistics: true,
      notifyUser: true,
      notifySecurityChief: false,
      notifySecurityGuard: false,
      additionalNotifications: '',
      customerId: TEST_COUNTRY_ID,
      autoCancelAfterExpired: true,
      allowsMultipleAuthorized: false,
      requiresDni: false,
      isPermanent: false,
      lotFrom: null,
      lotTo: null,
      emergency: false,
      requiresPatent: false,
      generateQr: false,
      reservation: true,
      notifyGiroVision: false,
      gvEntryTypeId: null,
      gvGuestTypeId: null,
    },
    {
      code: 'AA520',
      updatedById: STATESMAN,
      title: 'MAL ESTACIONAMIENTO',
      active: true,
      description: true,
      attachment: true,
      monitor: true,
      addToStatistics: true,
      notifyUser: true,
      notifySecurityChief: false,
      notifySecurityGuard: false,
      additionalNotifications: '',
      customerId: TEST_COUNTRY_ID,
      autoCancelAfterExpired: false,
      allowsMultipleAuthorized: false,
      requiresDni: false,
      isPermanent: false,
      lotFrom: null,
      lotTo: null,
      emergency: false,
      requiresPatent: false,
      generateQr: false,
      reservation: false,
      notifyGiroVision: false,
      gvEntryTypeId: null,
      gvGuestTypeId: null,
    },
    {
      code: 'ZZ999',
      updatedById: STATESMAN,
      title: 'SOLICITAR AUTORIZACION',
      active: true,
      description: false,
      attachment: false,
      monitor: true,
      addToStatistics: true,
      notifyUser: true,
      notifySecurityChief: false,
      notifySecurityGuard: false,
      additionalNotifications: '',
      customerId: TEST_COUNTRY_ID,
      autoCancelAfterExpired: true,
      allowsMultipleAuthorized: false,
      requiresDni: false,
      isPermanent: false,
      lotFrom: 'Segu',
      lotTo: 'Segu',
      emergency: false,
      requiresPatent: false,
      generateQr: false,
      reservation: true,
      notifyGiroVision: true,
      gvEntryTypeId: null,
      gvGuestTypeId: null,
    },
    {
      code: 'ZZ100',
      updatedById: STATESMAN,
      title: 'Reserva Tenis',
      active: true,
      description: true,
      attachment: true,
      monitor: false,
      addToStatistics: true,
      notifyUser: true,
      notifySecurityChief: false,
      notifySecurityGuard: false,
      additionalNotifications: '',
      customerId: BOLIVAR_ID,
      autoCancelAfterExpired: true,
      allowsMultipleAuthorized: false,
      requiresDni: false,
      isPermanent: false,
      lotFrom: null,
      lotTo: null,
      emergency: false,
      requiresPatent: false,
      generateQr: false,
      reservation: true,
      eventCategoryId: null,
      notifyGiroVision: true,
      gvEntryTypeId: null,
      gvGuestTypeId: null,
    },
    {
      code: 'AA530',
      updatedById: STATESMAN,
      title: 'RESIDUOS FUERA DE HORARIO',
      active: true,
      description: true,
      attachment: true,
      monitor: true,
      addToStatistics: true,
      notifyUser: true,
      notifySecurityChief: false,
      notifySecurityGuard: false,
      additionalNotifications: '',
      customerId: BOLIVAR_ID,
      autoCancelAfterExpired: false,
      allowsMultipleAuthorized: false,
      requiresDni: false,
      isPermanent: false,
      lotFrom: '000',
      lotTo: '369',
      emergency: false,
      requiresPatent: false,
      generateQr: false,
      reservation: true,
      notifyGiroVision: false,
      gvEntryTypeId: null,
      gvGuestTypeId: null,
    },
    {
      code: 'AA540',
      updatedById: STATESMAN,
      title: 'PERDIDA DE AGUA',
      active: true,
      description: true,
      attachment: false,
      monitor: true,
      addToStatistics: true,
      notifyUser: true,
      notifySecurityChief: false,
      notifySecurityGuard: false,
      additionalNotifications: '',
      customerId: BOLIVAR_ID,
      autoCancelAfterExpired: false,
      allowsMultipleAuthorized: false,
      requiresDni: false,
      isPermanent: false,
      lotFrom: null,
      lotTo: null,
      emergency: false,
      requiresPatent: false,
      generateQr: false,
      reservation: true,
      notifyGiroVision: true,
      gvEntryTypeId: null,
      gvGuestTypeId: null,
    },
    {
      id: LIST_VISITORS,
      code: 'AA101',
      updatedById: STATESMAN,
      title: 'LISTA DE VISITAS',
      active: true,
      description: false,
      attachment: false,
      monitor: true,
      addToStatistics: true,
      notifyUser: true,
      notifySecurityChief: false,
      notifySecurityGuard: false,
      additionalNotifications: '',
      customerId: TEST_COUNTRY_ID,
      autoCancelAfterExpired: true,
      allowsMultipleAuthorized: true,
      requiresDni: false,
      isPermanent: false,
      lotFrom: null,
      lotTo: null,
      emergency: false,
      requiresPatent: false,
      generateQr: false,
      reservation: false,
      notifyGiroVision: true,
      gvEntryTypeId: null,
      gvGuestTypeId: null,
    },
    {
      id: '08520008-52a6-452f-9469-631e14f77149',
      code: 'AA0001',
      title: 'Poda de árboles',
      active: true,
      description: true,
      attachment: false,
      monitor: true,
      addToStatistics: true,
      notifyUser: true,
      notifySecurityChief: true,
      notifySecurityGuard: true,
      additionalNotifications: '[]',
      customerId: TEST_COUNTRY_ID,
      autoCancelAfterExpired: true,
      allowsMultipleAuthorized: false,
      requiresDni: false,
      isPermanent: false,
      lotFrom: null,
      lotTo: null,
      emergency: false,
      requiresPatent: false,
      generateQr: false,
      qrFormat: null,
      reservation: false,
      eventCategoryId: null,
      notifyGiroVision: false,
      gvEntryTypeId: null,
      gvGuestTypeId: null,
      updatedById: STATESMAN,
    },
    {
      id: 'bb3009dc-c215-49d3-baef-af893aa1dfe2',
      code: 'AA0002',
      title: 'Obstrucción de carretera',
      active: true,
      description: true,
      attachment: true,
      monitor: true,
      addToStatistics: true,
      notifyUser: true,
      notifySecurityChief: true,
      notifySecurityGuard: true,
      additionalNotifications: '[]',
      customerId: TEST_COUNTRY_ID,
      autoCancelAfterExpired: true,
      allowsMultipleAuthorized: false,
      requiresDni: false,
      isPermanent: false,
      lotFrom: null,
      lotTo: null,
      emergency: false,
      requiresPatent: false,
      generateQr: false,
      qrFormat: null,
      reservation: false,
      eventCategoryId: null,
      notifyGiroVision: false,
      gvEntryTypeId: null,
      gvGuestTypeId: null,
      updatedById: STATESMAN,
    },
    {
      id: 'c2b6597e-2150-4b16-bd1d-deb92ad713c8',
      code: 'AA003',
      title: 'Autorización de visitas',
      active: true,
      description: false,
      attachment: false,
      monitor: true,
      addToStatistics: true,
      notifyUser: true,
      notifySecurityChief: false,
      notifySecurityGuard: false,
      additionalNotifications: '[]',
      customerId: TEST_COUNTRY_ID,
      autoCancelAfterExpired: true,
      allowsMultipleAuthorized: false,
      requiresDni: false,
      isPermanent: false,
      lotFrom: null,
      lotTo: null,
      emergency: false,
      requiresPatent: false,
      generateQr: false,
      qrFormat: 0,
      reservation: false,
      eventCategoryId: VISITAS_TEST_COUNTRY_ID,
      notifyGiroVision: false,
      gvEntryTypeId: null,
      gvGuestTypeId: null,
      updatedById: STATESMAN,
    },
    {
      id: '1500dca3-3848-4fc8-8897-b3fac6851c6a',
      updatedById: STATESMAN,
      code: 'ZZ0001',
      title: 'Solicitar Autorización',
      active: true,
      description: false,
      attachment: false,
      monitor: true,
      addToStatistics: true,
      notifyUser: true,
      notifySecurityChief: false,
      notifySecurityGuard: false,
      additionalNotifications: '[]',
      customerId: TEST_COUNTRY_ID,
      autoCancelAfterExpired: true,
      allowsMultipleAuthorized: false,
      requiresDni: false,
      isPermanent: false,
      lotFrom: null,
      lotTo: null,
      emergency: false,
      requiresPatent: false,
      generateQr: false,
      qrFormat: null,
      reservation: false,
      eventCategoryId: null,
      notifyGiroVision: false,
      gvEntryTypeId: null,
      gvGuestTypeId: null,
    },
    {
      id: 'cc380198-7cbc-469f-8c98-c8b60d557740',
      updatedById: STATESMAN,
      code: 'QR',
      title: 'Genera PDF417',
      active: true,
      description: false,
      attachment: false,
      monitor: true,
      addToStatistics: true,
      notifyUser: true,
      notifySecurityChief: true,
      notifySecurityGuard: true,
      additionalNotifications: '[]',
      customerId: TEST_COUNTRY_ID,
      autoCancelAfterExpired: true,
      allowsMultipleAuthorized: false,
      requiresDni: true,
      isPermanent: false,
      lotFrom: null,
      lotTo: null,
      emergency: false,
      requiresPatent: false,
      generateQr: true,
      qrFormat: 1,
      reservation: false,
      eventCategoryId: VISITAS_TEST_COUNTRY_ID,
      notifyGiroVision: false,
      gvEntryTypeId: null,
      gvGuestTypeId: null,
    },
    {
      id: '01c5cb7c-f468-4f14-8c05-1af06d9065e2',
      updatedById: STATESMAN,
      code: 'QR2',
      title: 'QR DNI largo',
      active: true,
      description: false,
      attachment: false,
      monitor: true,
      addToStatistics: true,
      notifyUser: true,
      notifySecurityChief: true,
      notifySecurityGuard: true,
      additionalNotifications: '[]',
      customerId: TEST_COUNTRY_ID,
      autoCancelAfterExpired: true,
      allowsMultipleAuthorized: false,
      requiresDni: true,
      isPermanent: false,
      lotFrom: null,
      lotTo: null,
      emergency: false,
      requiresPatent: false,
      generateQr: true,
      qrFormat: 3,
      reservation: false,
      eventCategoryId: VISITAS_TEST_COUNTRY_ID,
      notifyGiroVision: false,
      gvEntryTypeId: null,
      gvGuestTypeId: null,
    },
    {
      id: 'c4369755-ec9d-4405-a260-abbb68a25c24',
      updatedById: STATESMAN,
      code: 'MUL DESC',
      title: 'Múltiple + Descripción Obligatoria',
      active: true,
      description: true,
      attachment: true,
      monitor: true,
      addToStatistics: true,
      notifyUser: true,
      notifySecurityChief: true,
      notifySecurityGuard: true,
      additionalNotifications: '[]',
      customerId: TEST_COUNTRY_ID,
      autoCancelAfterExpired: true,
      allowsMultipleAuthorized: true,
      requiresDni: false,
      isPermanent: false,
      lotFrom: null,
      lotTo: null,
      emergency: false,
      requiresPatent: false,
      generateQr: false,
      qrFormat: 0,
      reservation: false,
      eventCategoryId: VISITAS_TEST_COUNTRY_ID,
      notifyGiroVision: false,
      gvEntryTypeId: null,
      gvGuestTypeId: null,
    },
    {
      id: '493a6acb-ba7f-426c-954b-5d19a9f19f69',
      updatedById: STATESMAN,
      code: 'QR3',
      title: 'QR + DNI opcional',
      active: true,
      description: false,
      attachment: false,
      monitor: true,
      addToStatistics: true,
      notifyUser: true,
      notifySecurityChief: true,
      notifySecurityGuard: true,
      additionalNotifications: '[]',
      customerId: TEST_COUNTRY_ID,
      autoCancelAfterExpired: true,
      allowsMultipleAuthorized: false,
      requiresDni: false,
      isPermanent: false,
      lotFrom: null,
      lotTo: null,
      emergency: false,
      requiresPatent: false,
      generateQr: true,
      qrFormat: 2,
      reservation: false,
      eventCategoryId: null,
      notifyGiroVision: false,
      gvEntryTypeId: null,
      gvGuestTypeId: null,
    },
    {
      id: '1db0a162-d6e7-4d9d-b53d-8af2b731e2c5',
      updatedById: STATESMAN,
      code: 'YY100',
      title: 'Reserva Tenis',
      active: true,
      description: true,
      attachment: true,
      monitor: true,
      addToStatistics: true,
      notifyUser: true,
      notifySecurityChief: false,
      notifySecurityGuard: false,
      additionalNotifications: '[]',
      customerId: TEST_COUNTRY_ID,
      autoCancelAfterExpired: true,
      allowsMultipleAuthorized: false,
      requiresDni: false,
      isPermanent: false,
      lotFrom: null,
      lotTo: null,
      emergency: false,
      requiresPatent: false,
      generateQr: false,
      qrFormat: 0,
      reservation: true,
      eventCategoryId: null,
      notifyGiroVision: false,
      gvEntryTypeId: null,
      gvGuestTypeId: null,
    },
    {
      id: 'b4178903-10b9-4ddc-ba1d-99866e3ec4d2',
      updatedById: STATESMAN,
      code: 'YY200',
      title: 'Reserva Futbol',
      active: true,
      description: true,
      attachment: true,
      monitor: true,
      addToStatistics: true,
      notifyUser: true,
      notifySecurityChief: false,
      notifySecurityGuard: false,
      additionalNotifications: '[]',
      customerId: TEST_COUNTRY_ID,
      autoCancelAfterExpired: true,
      allowsMultipleAuthorized: false,
      requiresDni: false,
      isPermanent: false,
      lotFrom: null,
      lotTo: null,
      emergency: false,
      requiresPatent: false,
      generateQr: false,
      qrFormat: 0,
      reservation: true,
      eventCategoryId: null,
      notifyGiroVision: false,
      gvEntryTypeId: null,
      gvGuestTypeId: null,
    },
    {
      id: 'a237a1c3-b459-48bf-aded-75def1e76e6d',
      updatedById: STATESMAN,
      code: 'YY300',
      title: 'Reserva Golf',
      active: true,
      description: true,
      attachment: true,
      monitor: true,
      addToStatistics: true,
      notifyUser: true,
      notifySecurityChief: false,
      notifySecurityGuard: false,
      additionalNotifications: '[]',
      customerId: TEST_COUNTRY_ID,
      autoCancelAfterExpired: true,
      allowsMultipleAuthorized: false,
      requiresDni: false,
      isPermanent: false,
      lotFrom: null,
      lotTo: null,
      emergency: false,
      requiresPatent: false,
      generateQr: false,
      qrFormat: 0,
      reservation: true,
      eventCategoryId: null,
      notifyGiroVision: false,
      gvEntryTypeId: null,
      gvGuestTypeId: null,
    },
    {
      id: '20677846-5c3d-4630-9bdd-42fbc4a69820',
      updatedById: STATESMAN,
      code: 'YY400',
      title: 'Reserva HOUSE/SUM',
      active: true,
      description: true,
      attachment: true,
      monitor: true,
      addToStatistics: true,
      notifyUser: true,
      notifySecurityChief: false,
      notifySecurityGuard: false,
      additionalNotifications: '[]',
      customerId: TEST_COUNTRY_ID,
      autoCancelAfterExpired: true,
      allowsMultipleAuthorized: false,
      requiresDni: false,
      isPermanent: false,
      lotFrom: null,
      lotTo: null,
      emergency: false,
      requiresPatent: false,
      generateQr: false,
      qrFormat: 0,
      reservation: true,
      eventCategoryId: null,
      notifyGiroVision: false,
      gvEntryTypeId: null,
      gvGuestTypeId: null,
    },
  ],
  async run(prisma: PrismaClient) {
    return prisma.eventType.createMany({
      data: this.data,
      skipDuplicates: true,
    });
  },
};

export default model;
