import { Prisma, PrismaClient } from '@prisma/client';
import { Model } from '../seed';
import {
  constants,
  eventType,
  reservationType,
  reservationSpace,
} from '../utils/constants';

const { TEST_COUNTRY_ID, SAN_FERNANDO_ID } = constants;
const { LIST_VISITORS, SUPPLIERS } = eventType;
const { SUM, POOL, GOLF, TENNIS, SOCCER, YARD } = reservationType;
const {
  SUM_1_AFTERNOON,
  SUM_2_NIGHT,
  MATCH,
  MATCH_1,
  MATCH_2,
  MATCH_3,
  SOCCER_11,
  SOCCER_7,
  POOL: POOL_SPACE,
  YARD: YARD_SPACE,
  SIMULTANEOUS,
} = reservationSpace;

const model: Model & { data: Prisma.ReservationSpaceCreateManyInput[] } = {
  data: [
    {
      id: SUM_1_AFTERNOON,
      code: '1SUM Tarde',
      schedule: {
        mon: { from: '1400', to: '1800' },
        tue: { from: '1400', to: '1800' },
        wed: { from: '1400', to: '1800' },
        thu: { from: '1400', to: '1800' },
        fri: { from: '1400', to: '1800' },
        sat: { from: '1400', to: '1800' },
        sun: { from: '1400', to: '1800' },
      },
      interval: 240,
      notifyParticipants: false,
      additionalNumbers: '',
      active: true,
      reservationTypeId: SUM, // ID de Tipo de Reserva SUM
      eventTypeId: LIST_VISITORS,
      customerId: SAN_FERNANDO_ID,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: SUM_2_NIGHT,
      code: '2SUM Noche',
      schedule: {
        mon: { from: '1930', to: '0300' },
        tue: { from: '1930', to: '0300' },
        wed: { from: '1930', to: '0300' },
        thu: { from: '1930', to: '0300' },
        fri: { from: '1930', to: '0300' },
        sat: { from: '1930', to: '0300' },
        sun: { from: '1930', to: '0300' },
      },
      interval: 450,
      notifyParticipants: false,
      additionalNumbers: '',
      active: true,
      reservationTypeId: SUM, // ID de Tipo de Reserva SUM
      eventTypeId: LIST_VISITORS,
      customerId: SAN_FERNANDO_ID,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: MATCH,
      code: 'Cancha',
      schedule: {
        mon: { from: '0800', to: '1700' },
        tue: { from: '0800', to: '1700' },
        wed: { from: '0800', to: '1700' },
        thu: { from: '0800', to: '1700' },
        fri: { from: '0800', to: '1700' },
        sat: { from: '0800', to: '1700' },
        sun: { from: '0800', to: '1700' },
        holiday: { from: '0800', to: '2100' },
        holidayEve: { from: '0800', to: '2100' },
      },
      interval: 12,
      notifyParticipants: true,
      additionalNumbers: '',
      active: true,
      reservationTypeId: GOLF, // ID de Tipo de Reserva Golf
      eventTypeId: LIST_VISITORS,
      customerId: TEST_COUNTRY_ID,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: MATCH_1,
      code: 'Cancha 1',
      schedule: {
        mon: { from: '0800', to: '2200' },
        tue: { from: '0800', to: '2200' },
        wed: { from: '0800', to: '2200' },
        thu: { from: '0800', to: '2200' },
        fri: { from: '0800', to: '2200' },
        sat: { from: '0800', to: '2200' },
        sun: { from: '0800', to: '2100' },
        holiday: { from: '0800', to: '2100' },
        holidayEve: { from: '0800', to: '2100' },
      },
      interval: 60,
      notifyParticipants: true,
      additionalNumbers: '',
      active: true,
      reservationTypeId: TENNIS, // ID de Tipo de Reserva Tenis
      eventTypeId: LIST_VISITORS,
      customerId: TEST_COUNTRY_ID,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: MATCH_2,
      code: 'Cancha 2',
      schedule: {
        mon: { from: '0800', to: '2200' },
        tue: { from: '0800', to: '2200' },
        wed: { from: '0800', to: '2200' },
        thu: { from: '0800', to: '2200' },
        fri: { from: '0800', to: '2200' },
        sat: { from: '0800', to: '2200' },
        sun: { from: '0800', to: '2200' },
        holiday: { from: '0800', to: '2100' },
        holidayEve: { from: '0800', to: '2100' },
      },
      interval: 60,
      notifyParticipants: true,
      additionalNumbers: '',
      active: true,
      reservationTypeId: TENNIS, // ID de Tipo de Reserva Tenis
      eventTypeId: LIST_VISITORS,
      customerId: TEST_COUNTRY_ID,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: MATCH_3,
      code: 'Cancha 3',
      schedule: {
        mon: { from: '0800', to: '2200' },
        tue: { from: '0800', to: '2200' },
        wed: { from: '0800', to: '2200' },
        thu: { from: '0800', to: '2200' },
        fri: { from: '0800', to: '2200' },
        sat: { from: '0800', to: '2200' },
        sun: { from: '0800', to: '2200' },
      },
      interval: 60,
      notifyParticipants: true,
      additionalNumbers: '',
      active: true,
      reservationTypeId: TENNIS, // ID de Tipo de Reserva Tenis
      eventTypeId: LIST_VISITORS,
      customerId: TEST_COUNTRY_ID,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: SOCCER_11,
      code: 'Futbol 11',
      schedule: {
        mon: { from: '0800', to: '1700' },
        tue: { from: '0800', to: '1700' },
        wed: { from: '0800', to: '1700' },
        thu: { from: '0800', to: '1700' },
        fri: { from: '0800', to: '1700' },
        sat: { from: '0800', to: '1700' },
        sun: { from: '0800', to: '1700' },
      },
      interval: 120,
      notifyParticipants: true,
      additionalNumbers: '',
      active: true,
      reservationTypeId: SOCCER, // ID de Tipo de Reserva Futbol
      eventTypeId: SUPPLIERS,
      customerId: SAN_FERNANDO_ID,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: SOCCER_7,
      code: 'Futbol 7',
      schedule: {
        mon: { from: '0800', to: '1700' },
        tue: { from: '0800', to: '1700' },
        wed: { from: '0800', to: '1700' },
        thu: { from: '0800', to: '1700' },
        fri: { from: '0800', to: '1700' },
        sat: { from: '0800', to: '1700' },
        sun: { from: '0800', to: '1700' },
      },
      interval: 90,
      notifyParticipants: true,
      additionalNumbers: '',
      active: true,
      reservationTypeId: SOCCER, // ID de Tipo de Reserva Futbol
      eventTypeId: SUPPLIERS,
      customerId: SAN_FERNANDO_ID,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: POOL_SPACE,
      code: 'Pileta',
      schedule: {
        mon: { from: '0900', to: '2000' },
        tue: { from: '0900', to: '2000' },
        wed: { from: '0900', to: '2000' },
        thu: { from: '0900', to: '2000' },
        fri: { from: '0900', to: '2000' },
        sat: { from: '0900', to: '2000' },
        sun: { from: '0900', to: '2000' },
      },
      interval: 45,
      notifyParticipants: true,
      additionalNumbers: '',
      active: true,
      reservationTypeId: POOL, // ID de Tipo de Reserva Pileta
      eventTypeId: SUPPLIERS,
      customerId: SAN_FERNANDO_ID,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: YARD_SPACE,
      code: 'Quincho',
      schedule: {
        mon: { from: '1100', to: '2359' },
        tue: { from: '0900', to: '2000' },
        wed: { from: '0900', to: '2000' },
        thu: { from: '0900', to: '2000' },
        fri: { from: '0900', to: '2000' },
        sat: { from: '0900', to: '2000' },
        sun: { from: '0900', to: '2000' },
      },
      interval: 388,
      notifyParticipants: true,
      additionalNumbers: '',
      active: true,
      reservationTypeId: YARD, // ID de Tipo de Reserva Quincho
      eventTypeId: LIST_VISITORS,
      customerId: TEST_COUNTRY_ID,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: SIMULTANEOUS,
      code: 'Simultanea',
      schedule: { sat: { from: '0900', to: '1700' } },
      interval: 300,
      notifyParticipants: true,
      additionalNumbers: '',
      active: false,
      reservationTypeId: GOLF, // ID de Tipo de Reserva Golf
      eventTypeId: LIST_VISITORS,
      customerId: TEST_COUNTRY_ID,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
  ],
  async run(prisma: PrismaClient) {
    return prisma.reservationSpace.createMany({
      data: this.data,
      skipDuplicates: true,
    });
  },
};

export default model;
