import { Prisma, PrismaClient } from '@prisma/client';
import { Model } from '../seed';
import {
  eventState,
  finalUser,
  constants,
  reservationSpace,
  reservationMode,
  reservationType,
  authorizedUser,
} from '../utils/constants';

const { TEST_COUNTRY_ID } = constants;
const { GOLF, TENNIS, SOCCER, SUM } = reservationType;
const { FINAL_USER_FERNANDO, FINAL_USER_NERINA } = finalUser;
const { AUTHORIZED_USER_FERNANDO, AUTHORIZED_USER_NERINA } = authorizedUser;
const { PRACTICE_9_HOLES, SINGLE, TOURNAMENT, SOCCER_7, SUM_MEETINGS } =
  reservationMode;
const {
  MATCH,
  MATCH_1,
  SOCCER_7: SOCCER_7_SPACE,
  SUM_2_NIGHT,
  SUM_1_AFTERNOON,
} = reservationSpace;
const { ATENDIDO, EMITIDO } = eventState;

const model: Model & {
  data: Prisma.ReservationCreateManyInput[];
} = {
  data: [
    {
      fromDate: new Date('2021-02-01 16:00:00'),
      toDate: new Date('2021-02-01 16:12:00'),
      inactiveToDate: new Date('2021-02-01 18:00:00'),
      numberOfGuests: 1,
      createdById: FINAL_USER_FERNANDO,
      lot: 'DS123456',
      userId: FINAL_USER_FERNANDO,
      authorizedUserId: AUTHORIZED_USER_FERNANDO,
      customerId: TEST_COUNTRY_ID,
      reservationTypeId: GOLF,
      reservationModeId: PRACTICE_9_HOLES,
      reservationSpaceId: MATCH,
      eventStateId: ATENDIDO,
    },
    {
      fromDate: new Date('2021-02-01 16:00:00'),
      toDate: new Date('2021-02-01 17:00:00'),
      inactiveToDate: new Date('2021-02-01 17:00:00'),
      cancelDate: new Date('2021-02-01 15:52:51'),
      numberOfGuests: 2,
      lot: null,
      userId: FINAL_USER_NERINA,
      authorizedUserId: AUTHORIZED_USER_NERINA,
      customerId: TEST_COUNTRY_ID,
      reservationTypeId: TENNIS,
      reservationModeId: SINGLE,
      reservationSpaceId: MATCH_1,
      createdById: FINAL_USER_NERINA,
      eventStateId: ATENDIDO,
    },
    {
      fromDate: new Date('2021-02-01 16:00:00'),
      toDate: new Date('2021-02-01 16:12:00'),
      inactiveToDate: new Date('2021-02-01 20:00:00'),
      numberOfGuests: 1,
      createdById: FINAL_USER_NERINA,
      userId: FINAL_USER_NERINA,
      authorizedUserId: AUTHORIZED_USER_NERINA,
      customerId: TEST_COUNTRY_ID,
      reservationTypeId: GOLF,
      reservationModeId: TOURNAMENT,
      reservationSpaceId: MATCH,
      eventStateId: EMITIDO,
    },
    {
      fromDate: new Date('2021-02-01 18:00:00'),
      toDate: new Date('2021-02-01 19:00:00'),
      inactiveToDate: new Date('2021-02-01 19:00:00'),
      cancelDate: new Date('2021-02-01 17:45:55'),
      numberOfGuests: 2,
      createdById: FINAL_USER_FERNANDO,
      userId: FINAL_USER_FERNANDO,
      authorizedUserId: AUTHORIZED_USER_FERNANDO,
      customerId: TEST_COUNTRY_ID,
      reservationTypeId: TENNIS,
      reservationModeId: SINGLE,
      reservationSpaceId: MATCH_1,
      eventStateId: ATENDIDO,
    },
    {
      fromDate: new Date('2021-02-02 17:00:00'),
      toDate: new Date('2021-02-02 18:30:00'),
      inactiveToDate: new Date('2021-02-02 18:30:00'),
      numberOfGuests: 0,
      createdById: FINAL_USER_NERINA,
      lot: 'DS123456',
      userId: FINAL_USER_NERINA,
      authorizedUserId: AUTHORIZED_USER_NERINA,
      customerId: TEST_COUNTRY_ID,
      reservationTypeId: SOCCER,
      reservationModeId: SOCCER_7,
      reservationSpaceId: SOCCER_7_SPACE,
      eventStateId: EMITIDO,
      file: {
        container: 'reservations_file',
        name: 'f370b379-d177-4705-88a3-d0b26af92059.jpeg',
        type: 'image/jpeg',
        size: 149519,
        url: 'https://s3.amazonaws.com/uploads.countries.basapp.com.ar/reservations/file/f370b379-d177-4705-88a3-d0b26af92059.jpeg',
      },
    },
    {
      fromDate: new Date('2021-03-08 18:00:00'),
      toDate: new Date('2021-03-08 19:00:00'),
      inactiveToDate: new Date('2021-03-08 19:00:00'),
      numberOfGuests: 2,
      createdById: FINAL_USER_FERNANDO,
      lot: 'AA22',
      userId: FINAL_USER_FERNANDO,
      authorizedUserId: AUTHORIZED_USER_FERNANDO,
      customerId: TEST_COUNTRY_ID,
      reservationTypeId: TENNIS,
      reservationModeId: SINGLE,
      reservationSpaceId: MATCH_1,
      eventStateId: EMITIDO,
    },
    {
      fromDate: new Date('2021-04-12 13:00:00'),
      toDate: new Date('2021-04-12 14:00:00'),
      inactiveToDate: new Date('2021-04-12 14:00:00'),
      numberOfGuests: 2,
      createdById: FINAL_USER_FERNANDO,
      lot: 'AA22',
      userId: FINAL_USER_FERNANDO,
      authorizedUserId: AUTHORIZED_USER_FERNANDO,
      customerId: TEST_COUNTRY_ID,
      reservationTypeId: TENNIS,
      reservationModeId: SINGLE,
      reservationSpaceId: MATCH_1,
      eventStateId: EMITIDO,
    },
    {
      fromDate: new Date('2021-09-04 16:00:00'),
      toDate: new Date('2021-09-04 17:00:00'),
      inactiveToDate: new Date('2021-09-04 17:00:00'),
      numberOfGuests: 2,
      createdById: FINAL_USER_FERNANDO,
      lot: 'DS123456',
      userId: FINAL_USER_FERNANDO,
      authorizedUserId: AUTHORIZED_USER_FERNANDO,
      customerId: TEST_COUNTRY_ID,
      reservationTypeId: TENNIS,
      reservationModeId: SINGLE,
      reservationSpaceId: MATCH_1,
      eventStateId: EMITIDO,
    },
    {
      fromDate: new Date('2021-09-04 17:00:00'),
      toDate: new Date('2021-09-04 18:00:00'),
      inactiveToDate: new Date('2021-09-04 18:00:00'),
      numberOfGuests: 2,
      createdById: FINAL_USER_FERNANDO,
      lot: '',
      userId: FINAL_USER_FERNANDO,
      authorizedUserId: AUTHORIZED_USER_FERNANDO,
      customerId: TEST_COUNTRY_ID,
      reservationTypeId: TENNIS,
      reservationModeId: SINGLE,
      reservationSpaceId: MATCH_1,
      eventStateId: EMITIDO,
    },
    {
      fromDate: new Date('2021-09-04 18:00:00'),
      toDate: new Date('2021-09-04 19:00:00'),
      inactiveToDate: new Date('2021-09-04 19:00:00'),
      numberOfGuests: 2,
      createdById: FINAL_USER_FERNANDO,
      lot: '',
      userId: FINAL_USER_FERNANDO,
      authorizedUserId: AUTHORIZED_USER_FERNANDO,
      customerId: TEST_COUNTRY_ID,
      reservationTypeId: TENNIS,
      reservationModeId: SINGLE,
      reservationSpaceId: MATCH_1,
      eventStateId: EMITIDO,
    },
    {
      fromDate: new Date('2021-09-04 21:00:00'),
      toDate: new Date('2021-09-04 22:00:00'),
      inactiveToDate: new Date('2021-09-04 22:00:00'),
      numberOfGuests: 2,
      createdById: FINAL_USER_FERNANDO,
      lot: 'DS123456',
      userId: FINAL_USER_FERNANDO,
      authorizedUserId: AUTHORIZED_USER_FERNANDO,
      customerId: TEST_COUNTRY_ID,
      reservationTypeId: TENNIS,
      reservationModeId: SINGLE,
      reservationSpaceId: MATCH_1,
      eventStateId: EMITIDO,
    },
    {
      fromDate: new Date('2021-10-12 13:00:00'),
      toDate: new Date('2021-10-12 14:00:00'),
      inactiveToDate: new Date('2021-10-12 14:00:00'),
      numberOfGuests: 2,
      createdById: FINAL_USER_FERNANDO,
      lot: 'DS123456',
      userId: FINAL_USER_FERNANDO,
      authorizedUserId: AUTHORIZED_USER_FERNANDO,
      customerId: TEST_COUNTRY_ID,
      reservationTypeId: TENNIS,
      reservationModeId: SINGLE,
      reservationSpaceId: MATCH_1,
      eventStateId: ATENDIDO,
    },
    {
      fromDate: new Date('2021-11-24 21:00:00'),
      toDate: new Date('2021-11-24 22:00:00'),
      inactiveToDate: new Date('2021-11-24 22:00:00'),
      numberOfGuests: 2,
      createdById: FINAL_USER_NERINA,
      lot: 'DS123456',
      userId: FINAL_USER_NERINA,
      authorizedUserId: AUTHORIZED_USER_NERINA,
      customerId: TEST_COUNTRY_ID,
      reservationTypeId: TENNIS,
      reservationModeId: SINGLE,
      reservationSpaceId: MATCH_1,
      eventStateId: EMITIDO,
    },
    {
      fromDate: new Date('2021-11-26 14:00:00'),
      toDate: new Date('2021-11-26 15:00:00'),
      inactiveToDate: new Date('2021-11-26 15:00:00'),
      numberOfGuests: 2,
      createdById: FINAL_USER_NERINA,
      userId: FINAL_USER_NERINA,
      authorizedUserId: AUTHORIZED_USER_NERINA,
      customerId: TEST_COUNTRY_ID,
      reservationTypeId: TENNIS,
      reservationModeId: SINGLE,
      reservationSpaceId: MATCH_1,
      eventStateId: EMITIDO,
    },
    {
      fromDate: new Date('2021-11-26 17:00:00'),
      toDate: new Date('2021-11-26 18:00:00'),
      inactiveToDate: new Date('2021-11-26 18:00:00'),
      numberOfGuests: 2,
      createdById: FINAL_USER_FERNANDO,
      userId: FINAL_USER_FERNANDO,
      authorizedUserId: AUTHORIZED_USER_FERNANDO,
      customerId: TEST_COUNTRY_ID,
      reservationTypeId: TENNIS,
      reservationModeId: SINGLE,
      reservationSpaceId: MATCH_1,
      eventStateId: EMITIDO,
    },
    {
      fromDate: new Date('2021-11-26 21:00:00'),
      toDate: new Date('2021-11-26 22:00:00'),
      inactiveToDate: new Date('2021-11-26 22:00:00'),
      numberOfGuests: 2,
      createdById: FINAL_USER_FERNANDO,
      lot: '',
      userId: FINAL_USER_FERNANDO,
      authorizedUserId: AUTHORIZED_USER_FERNANDO,
      customerId: TEST_COUNTRY_ID,
      reservationTypeId: TENNIS,
      reservationModeId: SINGLE,
      reservationSpaceId: MATCH_1,
      eventStateId: EMITIDO,
    },
    {
      fromDate: new Date('2021-11-26 22:00:00'),
      toDate: new Date('2021-11-26 23:00:00'),
      inactiveToDate: new Date('2021-11-26 23:00:00'),
      numberOfGuests: 2,
      createdById: FINAL_USER_FERNANDO,
      lot: 'DS123456',
      userId: FINAL_USER_FERNANDO,
      authorizedUserId: AUTHORIZED_USER_FERNANDO,
      customerId: TEST_COUNTRY_ID,
      reservationTypeId: TENNIS,
      reservationModeId: SINGLE,
      reservationSpaceId: MATCH_1,
      eventStateId: EMITIDO,
    },
    {
      fromDate: new Date('2021-11-27 22:30:00'),
      toDate: new Date('2021-11-28 06:00:00'),
      inactiveToDate: new Date('2021-11-27 22:31:00'),
      numberOfGuests: 0,
      createdById: FINAL_USER_FERNANDO,
      lot: 'DS123456',
      userId: FINAL_USER_FERNANDO,
      authorizedUserId: AUTHORIZED_USER_FERNANDO,
      customerId: TEST_COUNTRY_ID,
      reservationTypeId: SUM,
      reservationModeId: SUM_MEETINGS,
      reservationSpaceId: SUM_2_NIGHT,
      eventStateId: EMITIDO,
      file: {
        container: 'reservations_file',
        name: 'a0208416-f509-42bf-8b38-25245f9f9bd0.jpeg',
        type: 'image/jpeg',
        size: 523290,
        url: 'https://s3.amazonaws.com/uploads.countries.basapp.com.ar/reservations/file/a0208416-f509-42bf-8b38-25245f9f9bd0.jpeg',
      },
    },
    {
      fromDate: new Date('2022-04-06 00:00:00'),
      toDate: new Date('2022-04-06 01:00:00'),
      inactiveToDate: new Date('2022-04-06 01:00:00'),
      numberOfGuests: 2,
      createdById: FINAL_USER_FERNANDO,
      lot: 'DS123456',
      userId: FINAL_USER_FERNANDO,
      authorizedUserId: AUTHORIZED_USER_FERNANDO,
      customerId: TEST_COUNTRY_ID,
      reservationTypeId: TENNIS,
      reservationModeId: SINGLE,
      reservationSpaceId: MATCH_1,
      eventStateId: EMITIDO,
    },
    {
      fromDate: new Date('2022-04-06 00:00:00'),
      toDate: new Date('2022-04-06 01:00:00'),
      inactiveToDate: new Date('2022-04-06 01:00:00'),
      numberOfGuests: 2,
      createdById: FINAL_USER_FERNANDO,
      lot: 'DS123456',
      userId: FINAL_USER_FERNANDO,
      authorizedUserId: AUTHORIZED_USER_FERNANDO,
      customerId: TEST_COUNTRY_ID,
      reservationTypeId: TENNIS,
      reservationModeId: SINGLE,
      reservationSpaceId: MATCH_1,
      eventStateId: EMITIDO,
    },
    {
      fromDate: new Date('2022-04-06 17:00:00'),
      toDate: new Date('2022-04-06 21:00:00'),
      inactiveToDate: new Date('2022-04-06 17:01:00'),
      numberOfGuests: 0,
      createdById: FINAL_USER_FERNANDO,
      lot: 'DS123456',
      userId: FINAL_USER_FERNANDO,
      authorizedUserId: AUTHORIZED_USER_FERNANDO,
      customerId: TEST_COUNTRY_ID,
      reservationTypeId: SUM,
      reservationModeId: SUM_MEETINGS,
      reservationSpaceId: SUM_1_AFTERNOON,
      eventStateId: EMITIDO,
      file: {
        container: 'reservations_file',
        name: '6d36425c-c06a-4184-900f-a4a283aa7bad.jpeg',
        type: 'image/jpeg',
        size: 2459840,
        url: 'https://s3.amazonaws.com/uploads.countries.basapp.com.ar/reservations/file/6d36425c-c06a-4184-900f-a4a283aa7bad.jpeg',
      },
    },
    {
      fromDate: new Date('2022-05-09 21:00:00'),
      toDate: new Date('2022-05-09 22:00:00'),
      inactiveToDate: new Date('2022-05-09 22:00:00'),
      numberOfGuests: 2,
      createdById: FINAL_USER_FERNANDO,
      userId: FINAL_USER_FERNANDO,
      authorizedUserId: AUTHORIZED_USER_FERNANDO,
      customerId: TEST_COUNTRY_ID,
      reservationTypeId: TENNIS,
      reservationModeId: SINGLE,
      reservationSpaceId: MATCH_1,
      eventStateId: EMITIDO,
    },
  ],
  async run(prisma: PrismaClient) {
    return prisma.reservation.createMany({
      data: this.data,
      skipDuplicates: true,
    });
  },
};

export default model;
