export const errorCodes = {
  CUSTOMER_NOT_FOUND: 'CUSTOMER_NOT_FOUND',
  EVENT_TYPE_NOT_FOUND: 'EVENT_TYPE_NOT_FOUND',
  INVALID_ALERT_TYPE: 'INVALID_ALERT_TYPE',
  INVALID_CUSTOMER: 'INVALID_CUSTOMER',
  INVALID_NAME: 'INVALID_NAME',
  INVALID_SECRET_KEY: 'INVALID_SECRET_KEY',
  INVALID_EVENT_CATEGORY: 'INVALID_EVENT_CATEGORY',
  INVALID_UPDATE_EVENT: 'INVALID_UPDATE_EVENT',
  AUTHORIZATION_REQUIRED: 'AUTHORIZATION_REQUIRED',
  EVENT_NOT_FOUND: 'EVENT_NOT_FOUND',
  ER_DUP_ENTRY: 'ER_DUP_ENTRY',
  INVALID_CUSTOMER_EVENT_CATEGORY: 'INVALID_CUSTOMER_EVENT_CATEGORY',
};
