export const errorCodes = {
  INVALID_CUSTOMER: 'INVALID_CUSTOMER',
  LOCATION_NOT_FOUND: 'LOCATION_NOT_FOUND',
  NOTIFICATION_NOT_FOUND: 'NOTIFICATION_NOT_FOUND',
  PANIC_NOTIFICATION_EMPTY: 'PANIC_NOTIFICATION_EMPTY',
  PANIC_NOTIFICATION_NOT_REGISTERED: 'PANIC_NOTIFICATION_NOT_REGISTERED',
  USERS_LOT_NOT_FOUND: 'USERS_LOT_NOT_FOUND',
};
