export const errorCodes = {
  INVALID_DUPLICATED_LOT: 'INVALID_DUPLICATED_LOT',
  LOT_NOT_FOUND: 'LOT_NOT_FOUND',
  INVALID_FILE: 'INVALID_FILE',
  INTERNAL_SERVER_ERROR_LOT: 'INTERNAL_SERVER_ERROR_LOT',
  INVALID_FILE_EXTENSION: 'INVALID_FILE_EXTENSION',
};
