export const errorCodes = {
  INVALID_CUSTOMER: 'INVALID_CUSTOMER',
  CUSTOMER_LOT_NOT_FOUND: 'CUSTOMER_LOT_NOT_FOUND',
  INVALID_FILE: 'INVALID_FILE',
  INVALID_FILE_EXTENSION: 'INVALID_FILE_EXTENSION',
};
