export const errorCodes = {
  EXPIRED_TOKEN: 'EXPIRED_TOKEN',
  EXIST_CONTACT: 'EXIST_CONTACT',
  INVALID_CUSTOMER_SETTINGS: 'INVALID_CUSTOMER_SETTINGS',
  INVALID_ALERT_TYPE: 'INVALID_ALERT_TYPE',
  INVALID_CUSTOMER: 'INVALID_CUSTOMER',
  INVALID_EVENT_TYPE: 'INVALID_EVENT_TYPE',
  INVALID_TOKEN: 'INVALID_TOKEN',
  INVALID_USER_CUSTOMER: 'INVALID_USER_CUSTOMER',
  INVALID_USER_ROLE: 'INVALID_USER_ROLE',
  INVALID_USER: 'INVALID_USER',
  INVALID_USERNAME_PASSWORD: 'INVALID_USERNAME_PASSWORD',
  INVALID_USERNAME: 'INVALID_USERNAME',
  MAIL_DELIVERY_FAILED: 'MAIL_DELIVERY_FAILED',
  NOT_ACTIVE_CUSTOMER: 'NOT_ACTIVE_CUSTOMER',
  NOT_ACTIVE_USER: 'NOT_ACTIVE_USER',
  USER_CANNOT_UPDATE_SELF: 'USER_CANNOT_UPDATE_SELF',
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  USERNAME_ALREADY_TAKEN: 'USERNAME_ALREADY_TAKEN',
  PASSWORDS_DONT_MATCH: 'PASSWORDS_DONT_MATCH',
  ONLY_SELF_PASSWORD_UPDATE_ALLOWED: 'ONLY_SELF_PASSWORD_UPDATE_ALLOWED',
  USER_NOT_AUTHORIZED: 'USER_NOT_AUTHORIZED',
  USER_AUTHORIZED_NOT_FOUND: 'USER_AUTHORIZED_NOT_FOUND',
  USER_AUTHORIZED_INACTIVE: 'USER_AUTHORIZED_INACTIVE',
  CUSTOMER_NOT_AUTHORIZED: 'CUSTOMER_NOT_AUTHORIZED',
  CONTACT_AND_USERNAME_ARE_THE_SAME: 'CONTACT_AND_USERNAME_ARE_THE_SAME',
  CONTACT_NOT_FOUND: 'CONTACT_NOT_FOUND',
  CUSTOMER_NOT_FOUND: 'CUSTOMER_NOT_FOUND',
  EVENT_STATE_NOT_FOUND: 'EVENT_STATE_NOT_FOUND',
};

export const notificationUsers = {
  title: {
    active: {
      true: 'Usuario activado',
      false: 'Usuario desactivado',
    },
    status: {
      active: 'Usuario activado',
      rejected: 'Usuario rechazado',
      disabled: 'Usuario desactivado',
    },
  },
  message: {
    active: {
      true: 'Fuiste dado de alta nuevamente para enviar alertas',
      false:
        'Fuiste dado de baja para enviar alertas. Contactate con tu administrador de country o barrio para más información',
    },
  },
};

export const blackListUser = ['password'];
