export const errorCodes = {
  RESERVATION_LOCK_NOT_FOUND: 'RESERVATION_LOCK_NOT_FOUND',
  RESERVATION_LOCK_EXIST: 'RESERVATION_LOCK_EXIST',
  INVALID_RESERVATION_TYPE: 'INVALID_RESERVATION_TYPE',
  INVALID_RESERVATION_SPACE: 'INVALID_RESERVATION_SPACE',
};
