export const errorCodes = {
  RESERVATION_NOT_FOUND: 'RESERVATION_NOT_FOUND',
  NOT_ACTIVE_USER: 'NOT_ACTIVE_USER',
  INVALID_RESERVATION_TIME: 'INVALID_RESERVATION_TIME',
  INVALID_RESERVATION_DATE: 'INVALID_RESERVATION_DATE',
  ERR_RESERVATION_MODE: 'ERR_RESERVATION_MODE',
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  CUSTOMER_NOT_FOUND: 'CUSTOMER_NOT_FOUND',
  AUTHORIZED_USER_NOT_FOUND: 'AUTHORIZED_USER_NOT_FOUND',
  RESERVATION_MODE_NOT_FOUND: 'RESERVATION_MODE_NOT_FOUND',
  RESERVATION_TYPE_NOT_FOUND: 'RESERVATION_TYPE_NOT_FOUND',
  RESERVATION_SPACE_NOT_FOUND: 'RESERVATION_SPACE_NOT_FOUND',
  USER_NOT_REGISTERED: 'USER_NOT_REGISTERED',
  RESERVATION_DOES_NOT_EXIST: 'RESERVATION_DOES_NOT_EXIST',
  NO_USERS_TO_NOTIFY: 'NO_USERS_TO_NOTIFY',
  EVENT_STATE_NOT_FOUND: 'EVENT_STATE_NOT_FOUND',
  INVALID_PARTICIPANT: 'INVALID_PARTICIPANT',
  RESERVATION_CAN_NOT_BE_CANCELED: 'RESERVATION_CAN_NOT_BE_CANCELED',
};

export const listDays = ['sun', 'mon', 'tue', 'wed', 'thu', 'fri', 'sat'];

export const CANCELLED = 'Cancelado';
export const TOBECONFIRMED = 'A confirmar';
export const EMITTED = 'Emitido';
