export const errorCodes = {
  EVENT_NOT_ASSIGNED: 'EVENT_NOT_ASSIGNED',
  USERS_WITH_LOT_NOT_FOUND: 'USERS_WITH_LOT_NOT_FOUND',
  ALREADY_REJECTED: 'ALREADY_REJECTED',
  ALREADY_CONFIRMED: 'ALREADY_CONFIRMED',
  EVENT_AUTHORIZATION_REQUEST_NOT_FOUND:
    'EVENT_AUTHORIZATION_REQUEST_NOT_FOUND',
};
