export const errorCodes = {
  INVALID_RESERVATION_SPACE: 'INVALID_RESERVATION_SPACE',
  INVALID_RESERVATION_TYPE: 'INVALID_RESERVATION_TYPE',
  RESERVATION_MODE_NOT_FOUND: 'RESERVATION_MODE_NOT_FOUND',
};
